apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: platform
  description: Platform Engineering System
spec:
  owner: platform-team
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-platform
  description: Backstage Platform Application
  annotations:
    backstage.io/kubernetes-id: backstage
    backstage.io/kubernetes-namespace: backstage
    backstage.io/kubernetes-label-selector: 'app=backstage'
    argocd/app-name: backstage
    github.com/project-slug: kofiray/backstage-platform
    azure-devops/project: your-project
    azure-devops/build-definition: backstage-build
    signoz.io/service-name: backstage
    signoz.io/dashboard-url: /dashboard?service=backstage
  tags:
    - platform
    - backstage
    - kubernetes
  links:
    - url: https://backstage.kofiray.net
      title: Live Application
      icon: web
    - url: https://argocd.kofiray.net/applications/backstage
      title: Argo CD Deployment
      icon: deployment
    - url: http://signoz-frontend.observability.svc.cluster.local:3301/dashboard?service=backstage
      title: SigNoz Observability
      icon: monitoring
spec:
  type: service
  lifecycle: production
  owner: platform-team
  system: platform
  providesApis:
    - backstage-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: backstage-api
  description: Backstage Platform API
  annotations:
    backstage.io/kubernetes-id: backstage
    backstage.io/kubernetes-namespace: backstage
spec:
  type: openapi
  lifecycle: production
  owner: platform-team
  system: platform
  definition: |
    openapi: 3.0.0
    info:
      title: Backstage API
      version: 1.0.0
    paths:
      /api/catalog/entities:
        get:
          summary: List catalog entities
          responses:
            '200':
              description: Success
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sample-microservice
  description: Sample microservice demonstrating ALL platform capabilities
  annotations:
    # Kubernetes Integration
    backstage.io/kubernetes-id: sample-microservice
    backstage.io/kubernetes-namespace: apps
    backstage.io/kubernetes-label-selector: 'app=sample-microservice'
    
    # GitOps Integration
    argocd/app-name: sample-microservice
    crossplane.io/claim-name: sample-microservice-app
    crossplane.io/claim-namespace: crossplane-system
    
    # Source Control
    github.com/project-slug: kofiray/sample-microservice
    
    # Observability
    signoz.io/service-name: sample-microservice
    signoz.io/dashboard-url: /dashboard?service=sample-microservice
    grafana/dashboard-selector: service=sample-microservice
    datadog/dashboard-url: https://app.datadoghq.com/dashboard/abc-123
    newrelic.com/dashboard-guid: abc123def456
    
    # Security & Quality
    snyk.io/org-name: kofiray
    snyk.io/project-ids: abc123,def456
    sonarqube.org/project-key: sample-microservice
    lighthouse.com/website-url: https://sample-microservice.kofiray.net
    
    # Error Tracking
    sentry.io/project-slug: sample-microservice
    rollbar.com/project-name: sample-microservice
    
    # CI/CD
    jenkins.io/job-full-name: sample-microservice/main
    
    # Communication & Incidents
    slack.com/channel: #sample-microservice
    pagerduty.com/integration-key: abc123def456
    
    # Project Management
    jira/project-key: SAMP
    jira/component: sample-microservice
    
    # Secrets Management
    vault.io/secrets-path: secret/data/production/sample-microservice
    vault.io/secrets-engine: secret
    
  tags:
    - microservice
    - sample
    - kubernetes
    - crossplane
    - production
  links:
    - url: https://sample-microservice.kofiray.net
      title: Live Application
      icon: web
    - url: https://argocd.kofiray.net/applications/sample-microservice
      title: Argo CD Deployment
      icon: deployment
    - url: http://signoz-frontend.observability.svc.cluster.local:3301/dashboard?service=sample-microservice
      title: SigNoz Observability
      icon: monitoring
    - url: https://grafana.kofiray.net/d/sample-microservice
      title: Grafana Dashboard
      icon: dashboard
    - url: https://sonarqube.kofiray.net/dashboard?id=sample-microservice
      title: Code Quality
      icon: code
spec:
  type: service
  lifecycle: production
  owner: development-team
  system: platform
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: platform-team
  description: Platform Engineering Team
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: development-team
  description: Application Development Team
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: platform-admin
spec:
  memberOf: [platform-team]
