apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: platform
  description: Platform Engineering System
spec:
  owner: platform-team
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-platform
  description: Backstage Platform Application
  annotations:
    backstage.io/kubernetes-id: backstage
    backstage.io/kubernetes-namespace: backstage
    backstage.io/kubernetes-label-selector: 'app=backstage'
    argocd/app-name: backstage
    github.com/project-slug: your-org/backstage-platform
    azure-devops/project: your-project
    azure-devops/build-definition: backstage-build
    signoz.io/service-name: backstage
    signoz.io/dashboard-url: /dashboard?service=backstage
  tags:
    - platform
    - backstage
    - kubernetes
  links:
    - url: https://backstage.example.com
      title: Live Application
      icon: web
    - url: https://argocd.example.com/applications/backstage
      title: Argo CD Deployment
      icon: deployment
    - url: http://signoz-frontend.observability.svc.cluster.local:3301/dashboard?service=backstage
      title: SigNoz Observability
      icon: monitoring
spec:
  type: service
  lifecycle: production
  owner: platform-team
  system: platform
  providesApis:
    - backstage-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: backstage-api
  description: Backstage Platform API
  annotations:
    backstage.io/kubernetes-id: backstage
    backstage.io/kubernetes-namespace: backstage
spec:
  type: openapi
  lifecycle: production
  owner: platform-team
  system: platform
  definition: |
    openapi: 3.0.0
    info:
      title: Backstage API
      version: 1.0.0
    paths:
      /api/catalog/entities:
        get:
          summary: List catalog entities
          responses:
            '200':
              description: Success
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sample-microservice
  description: Sample microservice demonstrating platform capabilities
  annotations:
    backstage.io/kubernetes-id: sample-microservice
    backstage.io/kubernetes-namespace: apps
    backstage.io/kubernetes-label-selector: 'app=sample-microservice'
    argocd/app-name: sample-microservice
    github.com/project-slug: your-org/sample-microservice
    signoz.io/service-name: sample-microservice
    signoz.io/dashboard-url: /dashboard?service=sample-microservice
  tags:
    - microservice
    - sample
    - kubernetes
  links:
    - url: https://argocd.example.com/applications/sample-microservice
      title: Argo CD Deployment
      icon: deployment
    - url: http://signoz-frontend.observability.svc.cluster.local:3301/dashboard?service=sample-microservice
      title: SigNoz Observability
      icon: monitoring
spec:
  type: service
  lifecycle: experimental
  owner: development-team
  system: platform
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: platform-team
  description: Platform Engineering Team
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: development-team
  description: Application Development Team
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: platform-admin
spec:
  memberOf: [platform-team]
