---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.cilium.io/
    chart: cilium
    targetRevision: 1.14.5
    helm:
      values: |
        cluster:
          name: backstage-prod
          id: 1
        
        # GKE compatibility - use existing networking
        cni:
          install: false
        
        # Don't replace kube-proxy
        kubeProxyReplacement: "disabled"
        
        # Disable features that conflict with GKE
        nodeinit:
          enabled: false
        
        # Enable only ingress controller
        ingressController:
          enabled: true
          loadbalancerMode: shared
        
        # Enable Hubble for observability
        hubble:
          enabled: true
          relay:
            enabled: true
          ui:
            enabled: true
        
        # Minimal resource requirements
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Replace=true
