---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.cilium.io/
    chart: cilium
    targetRevision: 1.14.5
    helm:
      values: |
        cluster:
          name: backstage-prod
          id: 1
        
        # GKE specific configuration
        nodeinit:
          enabled: false
        
        # Use GKE's existing CNI
        cni:
          install: false
        
        # Enable ingress controller
        ingressController:
          enabled: true
          loadbalancerMode: shared
        
        # Enable Hubble for observability  
        hubble:
          enabled: true
          relay:
            enabled: true
          ui:
            enabled: true
        
        # Enable L7 proxy
        l7Proxy: true
        
        # Use existing kube-proxy
        kubeProxyReplacement: "partial"
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Replace=true
