---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: 7.0.19
    helm:
      values: |
        adminPassword: admin123
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: "gce"
            cert-manager.io/cluster-issuer: "letsencrypt-staging"
          hosts:
            - grafana.kofiray.net
          tls:
            - secretName: grafana-tls
              hosts:
                - grafana.kofiray.net
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
            - name: Prometheus
              type: prometheus
              url: http://prometheus:9090
              isDefault: true
        dashboardProviders:
          dashboardproviders.yaml:
            apiVersion: 1
            providers:
            - name: 'default'
              orgId: 1
              folder: ''
              type: file
              disableDeletion: false
              editable: true
              options:
                path: /var/lib/grafana/dashboards/default
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 55.5.0
    helm:
      values: |
        prometheus:
          prometheusSpec:
            resources:
              requests:
                cpu: 200m
                memory: 512Mi
              limits:
                cpu: 500m
                memory: 1Gi
            retention: 7d
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: standard-rwo
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 10Gi
        grafana:
          enabled: false  # We deploy Grafana separately
        alertmanager:
          alertmanagerSpec:
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 200m
                memory: 256Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.jenkins.io
    chart: jenkins
    targetRevision: 4.8.3
    helm:
      values: |
        controller:
          adminPassword: admin123
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: "gce"
              cert-manager.io/cluster-issuer: "letsencrypt-staging"
            hostName: jenkins.kofiray.net
            tls:
              - secretName: jenkins-tls
                hosts:
                  - jenkins.kofiray.net
          installPlugins:
            - kubernetes:3937.vd7b_82db_e347_b_
            - workflow-aggregator:590.v6a_d052e5a_a_b_5
            - git:4.13.0
            - configuration-as-code:1625.v27444588cc3d
        persistence:
          enabled: true
          size: 20Gi
          storageClass: standard-rwo
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarqube
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://SonarSource.github.io/helm-chart-sonarqube
    chart: sonarqube
    targetRevision: 10.2.0
    helm:
      values: |
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: "gce"
            cert-manager.io/cluster-issuer: "letsencrypt-staging"
          hosts:
            - name: sonarqube.kofiray.net
              path: /
          tls:
            - secretName: sonarqube-tls
              hosts:
                - sonarqube.kofiray.net
        resources:
          requests:
            cpu: 400m
            memory: 2Gi
          limits:
            cpu: 800m
            memory: 4Gi
        persistence:
          enabled: true
          size: 10Gi
          storageClass: standard-rwo
        postgresql:
          enabled: true
          postgresqlPassword: sonarqube123
          persistence:
            enabled: true
            size: 5Gi
            storageClass: standard-rwo
  destination:
    server: https://kubernetes.default.svc
    namespace: sonarqube
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
