apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-baseline
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kofiray/backstage-platform.git
    targetRevision: HEAD
    path: platform/k8s-baseline
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: v1.13.3
    helm:
      values: |
        installCRDs: true
        serviceAccount:
          annotations:
            iam.gke.io/gcp-service-account: cert-manager@docker-1210.iam.gserviceaccount.com
        securityContext:
          fsGroup: 1001
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 0.9.11
    helm:
      values: |
        serviceAccount:
          annotations:
            iam.gke.io/gcp-service-account: external-secrets@docker-1210.iam.gserviceaccount.com
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.crossplane.io/stable
    chart: crossplane
    targetRevision: 1.14.5
    helm:
      values: |
        resourcesCrossplane:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 200m
            memory: 512Mi
        resourcesRBACManager:
          limits:
            cpu: 200m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
        args:
          - --debug
          - --enable-composition-revisions
          - --enable-environment-configs
        metrics:
          enabled: true
        webhooks:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-providers
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kofiray/backstage-platform.git
    targetRevision: HEAD
    path: platform/manifests/crossplane
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: signoz
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kofiray/backstage-platform.git
    targetRevision: HEAD
    path: platform/manifests/signoz
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kofiray/backstage-platform.git
    targetRevision: HEAD
    path: platform/manifests/backstage
  destination:
    server: https://kubernetes.default.svc
    namespace: backstage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
# Monitoring and Development Tools
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: 7.0.19
    helm:
      values: |
        adminPassword: admin123
        ingress:
          enabled: true
          annotations:
            ingress.cilium.io/loadbalancer-mode: shared
            cert-manager.io/cluster-issuer: "letsencrypt-staging"
            nginx.ingress.kubernetes.io/whitelist-source-range: "86.177.222.87/32"
            nginx.ingress.kubernetes.io/whitelist-source-range: "86.177.222.87/32"
          ingressClassName: cilium
          hosts:
            - grafana.kofiray.net
          tls:
            - secretName: grafana-tls
              hosts:
                - grafana.kofiray.net
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.jenkins.io
    chart: jenkins
    targetRevision: 4.8.3
    helm:
      values: |
        controller:
          adminPassword: admin123
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
          ingress:
            enabled: true
            annotations:
              ingress.cilium.io/loadbalancer-mode: shared
              cert-manager.io/cluster-issuer: "letsencrypt-staging"
            nginx.ingress.kubernetes.io/whitelist-source-range: "86.177.222.87/32"
            ingressClassName: cilium
            hostName: jenkins.kofiray.net
            tls:
              - secretName: jenkins-tls
                hosts:
                  - jenkins.kofiray.net
        persistence:
          enabled: true
          size: 20Gi
          storageClass: standard-rwo
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarqube
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://SonarSource.github.io/helm-chart-sonarqube
    chart: sonarqube
    targetRevision: 10.2.0
    helm:
      values: |
        ingress:
          enabled: true
          annotations:
            ingress.cilium.io/loadbalancer-mode: shared
            cert-manager.io/cluster-issuer: "letsencrypt-staging"
            nginx.ingress.kubernetes.io/whitelist-source-range: "86.177.222.87/32"
          ingressClassName: cilium
          hosts:
            - name: sonarqube.kofiray.net
              path: /
          tls:
            - secretName: sonarqube-tls
              hosts:
                - sonarqube.kofiray.net
        resources:
          requests:
            cpu: 400m
            memory: 2Gi
          limits:
            cpu: 800m
            memory: 4Gi
        persistence:
          enabled: true
          size: 10Gi
          storageClass: standard-rwo
  destination:
    server: https://kubernetes.default.svc
    namespace: sonarqube
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lighthouse-ci
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kofiray/backstage-platform.git
    targetRevision: HEAD
    path: platform/manifests/lighthouse
  destination:
    server: https://kubernetes.default.svc
    namespace: lighthouse
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
# Cilium CNI and Ingress Controller
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.cilium.io/
    chart: cilium
    targetRevision: 1.14.5
    helm:
      values: |
        cluster:
          name: backstage-prod
          id: 1
        ingressController:
          enabled: true
          loadbalancerMode: shared
          service:
            type: LoadBalancer
        gatewayAPI:
          enabled: true
        hubble:
          enabled: true
          relay:
            enabled: true
          ui:
            enabled: true
            ingress:
              enabled: true
              annotations:
                cert-manager.io/cluster-issuer: "letsencrypt-staging"
            nginx.ingress.kubernetes.io/whitelist-source-range: "86.177.222.87/32"
              hosts:
                - hubble.kofiray.net
              tls:
                - secretName: hubble-tls
                  hosts:
                    - hubble.kofiray.net
        l7Proxy: true
        bandwidthManager:
          enabled: true
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        prometheus:
          enabled: true
        encryption:
          enabled: true
          type: wireguard
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
