---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lighthouse-ci
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kofiray/backstage-platform.git
    targetRevision: HEAD
    path: platform/manifests/lighthouse
  destination:
    server: https://kubernetes.default.svc
    namespace: lighthouse
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaeger
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://jaegertracing.github.io/helm-charts
    chart: jaeger
    targetRevision: 0.71.11
    helm:
      values: |
        provisionDataStore:
          cassandra: false
          elasticsearch: true
        storage:
          type: elasticsearch
        elasticsearch:
          replicas: 1
          minimumMasterNodes: 1
          resources:
            requests:
              cpu: 200m
              memory: 1Gi
            limits:
              cpu: 500m
              memory: 2Gi
        agent:
          enabled: false
        collector:
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 200m
              memory: 512Mi
        query:
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: "gce"
              cert-manager.io/cluster-issuer: "letsencrypt-staging"
            nginx.ingress.kubernetes.io/whitelist-source-range: "86.177.222.87/32"
            hosts:
              - jaeger.kofiray.net
            tls:
              - secretName: jaeger-tls
                hosts:
                  - jaeger.kofiray.net
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 200m
              memory: 512Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
